repos:
-   repo: local
    hooks:
    -   id: format
        name: format
        language: system
        entry: dotnet format  --no-restore
        pass_filenames: false

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
