version: 1
logger:
  console:
    level: verbose
cognite:
  project: "opcua-interface-test"
  host: "https://greenfield.cognitedata.com"
  idp-authentication:
    client-id: "09fb9354-1ec7-4ee7-a14a-416aa850e883"
    tenant: "b86328db-09aa-4f0e-9a03-0136f604d20a"
    secret: "cKC8Q~tNVQTkw30EETbfslglCd65~NM~LJ-MTbGq"
    scopes: 
      - "https://greenfield.cognitedata.com/.default"
manager:
  index: 0
  database-name: "db-test"
  table-name: "table-test"