version: 1
logger:
  console:
    level: verbose
cognite:
  project: "opcua-interface-test"
  host: "https://greenfield.cognitedata.com"
  idp-authentication:
    client-id: "09fb9354-1ec7-4ee7-a14a-416aa850e883"
    tenant: "b86328db-09aa-4f0e-9a03-0136f604d20a"
    secret: "gMi8Q~KHsBM5LNfftzRCnUyKBQi3NMkQ5Gma8cnP"
    scopes: 
      - "https://greenfield.cognitedata.com/.default"