version: 1
#logger:
#  console:
#    level: verbose
type: local
cognite:
  project: ${BF_TEST_PROJECT}
  host: ${BF_TEST_HOST}
  idp-authentication:
    client-id: ${BF_TEST_CLIENT_ID}
    tenant: ${BF_TEST_TENANT}
    secret: ${BF_TEST_SECRET}
    scopes:
      - ${BF_TEST_SCOPE}
  extraction-pipeline:
    external-id: net-remote-test
high-availability:
  index: 1
  raw:
    database-name: ${BF_TEST_DB}
    table-name: ${BF_TEST_TABLE}
  foo: bar
logger:
  console:
    level: debug
