name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Debug --no-restore /p:Version=1.0.0
    - name: Test
      run: dotnet test --no-restore --verbosity normal /p:Exclude="[*.Test]*" /p:Version=1.0.0 /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=TestResults/ ./ExtractorUtils.Test/
      env:
        TEST_API_KEY: ${{ secrets.TEST_API_KEY }}
        TEST_PROJECT: "extractor-tests"
        TEST_HOST: "https://greenfield.cognitedata.com"
        BF_TEST_PROJECT: "extractor-bluefield-testing"
        BF_TEST_HOST: "https://bluefield.cognitedata.com"
        BF_TEST_SCOPE: "https://bluefield.cognitedata.com/.default"
        BF_TEST_CLIENT_ID: ${{ secrets.BF_TEST_CLIENT_ID }}
        BF_TEST_TENANT: ${{ secrets.BF_TEST_TENANT }}
        BF_TEST_SECRET: ${{ secrets.BF_TEST_SECRET }}

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
