name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Fetch all history for all tags and branches
      run: git fetch --prune --unshallow
    - name: Show GitHub ref
      run: echo "$GITHUB_REF"
    - name: Get the version
      id: get_version
      run: echo ::set-env name=RELEASE_VERSION::${GITHUB_REF:10}    
    - name: Show GitHub Version
      run: echo "$RELEASE_VERSION"
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test
    - name: Create Nuget package
      run: dotnet pack ExtractorUtils/ExtractorUtils.csproj --output nuget-packages --configuration Release -p:PackageVersion=${{ env.RELEASE_VERSION }}
    - name: Push 
      run: dotnet nuget push nuget-packages/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
